spring:
  application:
    name: AQM-Car
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/aqm_car
    username: root
    password: root
  session:
    store-type: jdbc
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  messages:
    basename: message